name: app-build-action

# 改为允许手动点击按钮触发
on:
  workflow_dispatch:

jobs:
  build-tv:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      #签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      #设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      #更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_tv_app
          flutter pub get

      # 创建假的签名配置文件骗过 Gradle 检查（这是新加的这段）
      - name: Create dummy key.properties
        run: |
          echo "storeFile=dummy.jks" > simple_live_tv_app/android/key.properties
          echo "storePassword=dummy" >> simple_live_tv_app/android/key.properties
          echo "keyPassword=dummy" >> simple_live_tv_app/android/key.properties
          echo "keyAlias=dummy" >> simple_live_tv_app/android/key.properties

      #打包APK (改为不需要私钥的 debug 版本)
      - name: Build APK
        run: |
          cd simple_live_tv_app
          flutter build apk --debug --split-per-abi

      #上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv
          path: |
            simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-x86_64-debug.apk
